### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Mori-hub** [gaspardpetit/verbatim#11]
Hi Dear, please check this issue, thanks.

```
 from pyannote.core import Annotation
ModuleNotFoundError: No module named 'pyannote'
```

**Comment by gaspardpetit** [comment]
Thank you for reporting this - can you confirm that it happens when you tried to `pip install verbatim` and then execute `verbatim` from command line?

**Comment by gaspardpetit** [comment]
This should be resolved with commit 9560fe15183a7c3d8f9e6cc4a994f789a4ecd0c8

When I tested, I had to run the following:

```
pip uninstall verbatim
pip cache purge
pip install verbatim
```

In your case, `pip install --upgrade verbatim` might be sufficient.

Let me know if this resolved the issue on your side

**Comment by gaspardpetit** [comment]
Hello,

The two warnings reported are expected - I will mute them in the next release.

The `FileNotFoundError` error however suggests that the audio file could not be found. Can you provide more details about how you are invoking `verbatim`? Also, can you try running in verbose mode with `-vv` ?

**Comment by Mori-hub** [comment]
Please see this :
<img width="1276" alt="Untitled" src="https://github.com/gaspardpetit/verbatim/assets/53067774/fbe13840-b508-418d-8893-691518565070">

**Comment by gaspardpetit** [comment]
This is about missing ffmpeg, I added instructions - if you run the tool against a mp3, you must have ffmpeg installed in your path
