### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by Mori-hub** [gaspardpetit/verbatim#5]
Hi Dear,
Could you please add documentation of this great work, I mean how to use it.
Thanks a lot

**Comment by gaspardpetit** [comment]
Hey, thanks! I'm on it :)

**Comment by gaspardpetit** [comment]
Some of it is now documented but there will be more coming in the next couple of days

**Comment by gaspardpetit** [comment]
Added bash, docker and python documentation in the README
